// <auto-generated />
using FactorioWebInterface.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FactorioWebInterface.Migrations.ScenarioDb
{
    [DbContext(typeof(ScenarioDbContext))]
    [Migration("20181123110605_ScenarioDataEntry")]
    partial class ScenarioDataEntry
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("FactorioWebInterface.Data.ScenarioDataEntry", b =>
                {
                    b.Property<string>("DataSet");

                    b.Property<string>("Key");

                    b.Property<string>("Value")
                        .IsRequired();

                    b.HasKey("DataSet", "Key");

                    b.HasIndex("DataSet");

                    b.ToTable("ScenarioDataEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
